In [2]:
import numpy as np

# Basics 

In [3]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [4]:
b=np.array([[1.1,1.2,3.5],[2.4,5.6,4.5]])
print(b)

[[1.1 1.2 3.5]
 [2.4 5.6 4.5]]


#### Get dimentions

In [5]:
a.ndim

1

In [7]:
b.ndim


2

#### Get shape 

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

#### Get type 

In [11]:
a.dtype

dtype('int16')

In [12]:
b.dtype 

dtype('float64')

#### Get size (bytes for single item)

In [13]:
a.itemsize

2

In [15]:
b.itemsize 

8

#### Get totlal size (bytes for all arryay )

In [17]:
a.nbytes

6

In [19]:
b.nbytes

48

# Insilize defffirent types of array 

In [23]:
#all zeros matrix
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
#all ones matrix 
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#all with specific number
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [28]:
#all with specific number (full like) --> same shape
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [29]:
np.full(a.shape,4)

array([4, 4, 4])

In [41]:
#random decimal values 
np.random.rand(2,3)
               

array([[0.77277644, 0.70937217, 0.95951911],
       [0.23999783, 0.64315293, 0.31385454]])

In [36]:
#random decimal values with specific shape 
np.random.random_sample(a.shape)

array([0.97937529, 0.32563609, 0.29570987])

In [43]:
#specify stert and end
np.random.randint(3,8,size=(3,3))

array([[6, 6, 5],
       [6, 4, 3],
       [6, 5, 6]])

In [44]:
#identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
arr=np.array([[1,2,3]])
re=np.repeat(arr,3,axis=0)
print(re)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [57]:
test=np.ones((5,5))
print(test)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
test[1:4,1:4]=0
print(test)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
test[2,2]=9
print(test)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
#make matrix with start ,end and number of items
lin=np.linspace(0,10,150)
print(lin)

[ 0.          0.06711409  0.13422819  0.20134228  0.26845638  0.33557047
  0.40268456  0.46979866  0.53691275  0.60402685  0.67114094  0.73825503
  0.80536913  0.87248322  0.93959732  1.00671141  1.0738255   1.1409396
  1.20805369  1.27516779  1.34228188  1.40939597  1.47651007  1.54362416
  1.61073826  1.67785235  1.74496644  1.81208054  1.87919463  1.94630872
  2.01342282  2.08053691  2.14765101  2.2147651   2.28187919  2.34899329
  2.41610738  2.48322148  2.55033557  2.61744966  2.68456376  2.75167785
  2.81879195  2.88590604  2.95302013  3.02013423  3.08724832  3.15436242
  3.22147651  3.2885906   3.3557047   3.42281879  3.48993289  3.55704698
  3.62416107  3.69127517  3.75838926  3.82550336  3.89261745  3.95973154
  4.02684564  4.09395973  4.16107383  4.22818792  4.29530201  4.36241611
  4.4295302   4.4966443   4.56375839  4.63087248  4.69798658  4.76510067
  4.83221477  4.89932886  4.96644295  5.03355705  5.10067114  5.16778523
  5.23489933  5.30201342  5.36912752  5.43624161  5.

In [5]:
#make matrix with start ,end and seps value
arange=np.arange(0,10,1)
print(arange)

[0 1 2 3 4 5 6 7 8 9]


### Be carefull with copying !!


In [63]:
#if use this to compy a in b ,if you change b then a will change too 
a=np.array([1,2,2])
b=a
print(a)
print(b)

[1 2 2]
[1 2 2]


In [67]:
b[0]=3
print(a)
print(b)

[3 2 2]
[3 2 2]


In [68]:
#instade:
a=np.array([1,2,2])
b=np.copy(a)
print(a)
print(b)


[1 2 2]
[1 2 2]


In [69]:
b[0]=3
print(a)
print(b)

[1 2 2]
[3 2 2]


# Indexing and slicing 

In [8]:
a=np.array([1,2,3,4,5])

In [9]:
a[a>3]

array([4, 5])

#### NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements.

In [10]:
b=np.array(['menna','malak','doaa'])

In [13]:
v=np.vectorize(lambda s:s[0])(b)=='m'

In [14]:
b[v]

array(['menna', 'malak'], dtype='<U5')